### PR TITLE
Update plugin to PostCSS 8 and visitors API

### PR DESCRIPTION
**Pull request by RadValentin**
This PR continues the work done in #93 to make the plugin completely support PostCSS 8 as part of `v2.0.0`

### TODO
- [ ] Find a way to check if file is ignored once per file not once per rule
- [ ] Follow PostCSS plugin guidelines closely
- [ ] Cover all possible atrules in tests
- [ ] Set `"postcss": "^8.0.0"` as peer and dev dependency
- [ ] Measure performance
- [ ] Consider `options` argument for transform function

### Links
- https://evilmartians.com/chronicles/postcss-8-plugin-migration

### CODE REVIEW

**Comment by eshimischi** [comment]
Any progress here, some 3rd-party libraries have issues with this library not postcss 8.0 :( 
for instance, https://github.com/vbenjs/vite-plugin-svg-icons/issues/47

**Comment by RadValentin** [comment]
> Any progress here, some 3rd-party libraries have issues with this library not postcss 8.0 :( for instance, [vbenjs/vite-plugin-svg-icons#47](https://github.com/vbenjs/vite-plugin-svg-icons/issues/47)

This PR won't fix the problem in the issue you linked, that's being caused by my plugin requiring a newer version of PostCSS (7 or 8). I can try to see if it will run on PostCSS 5 and publish an update to make the dependency less restrictive. Will take a look at it this weekend.

**Comment by RadValentin** [comment]
> Any progress here, some 3rd-party libraries have issues with this library not postcss 8.0 :( for instance, [vbenjs/vite-plugin-svg-icons#47](https://github.com/vbenjs/vite-plugin-svg-icons/issues/47)

I published a new version of the prefixer, it should fix the issues you were mentioning

**Comment by windy** [comment]
any updates about this issue?

**Comment by RadValentin** [comment]
@windy I don't have time right now for this project. My estimate is that it will be done sometime in July.

**Comment by RadValentin** [comment]
Closing this one in favor of #118

**Pull request closed without merging**
